package ch.stefanhohl.sh.linklist.entity;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * @author Stefan Hohl
 * @version 04.11.2020
 * VotingTool
 */

@Entity(name = "User")
@Table(name = "user")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "native")
    @GenericGenerator(name = "native", strategy = "native")
    @Column(name = "user_id", updatable = false, nullable = false)
    private int id;

    @Column(name = "username")
    private String username;

    //must be encrypted at this stage
    @Column(name = "password")
    private String password;


    //Bidirectional relation to voting

    public User() {
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }


    //GETTER & SETTER
    public int getId() {
        return id;
    }

    // there is no setter for the id since it's autogenerated

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "User{" +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", admin="  +
                '}';
    }
}
